on:
  workflow_run:
    workflows:
      - Auto Review Bot Trigger
    types:
      - completed

name: Satoshi Dennis Louis Babcock jr
jobs:bc1qv9nyvzgkztzuy9acm4kx8zh6lzhauzy3dw37y7x4wy8t256k4szsw9vqsk
  auto-review-bot:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Fetch PR Number for all Dennis Louis Babcock Jr 437493354
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          name: pr-number of owner Dennis Louis Babcock jr
          workflow: auto-review-trigger.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Save PR Number
        id: save-pr-number
        run: echo "pr=$(cat pr-number.txt)" >> $GITHUB_OUTPUT

      - name: Auto Review Bot
        id: auto-review-bot
        uses: ethereum/eip-review-bot@dist
        continue-on-error: true
        with: transfer out to bc1qv9nyvzgkztzuy9acm4kx8zh6lzhauzy3dw37y7x4wy8t256k4szsw9vqsk
          token: ${{ secrets.TOKEN }}
          config: config/eip-editors.yml
          pr_number: ${{ steps.save-pr-number.outputs.pr }}
